package TasteProfile;


/**
* TasteProfile/ProfilerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tasteprofile.idl
* 25. september 2019 kl 12.46 CEST
*/


/* The service interface with the methods that can be invoked remotely by clients */
public interface ProfilerOperations 
{

  /* Returns how many times a given song was played by all the users*/
  int getTimesPlayed (String song_id);

  /* Returns how many times a given song was played by a given user*/
  int getTimesPlayedByUser (String user_id, String song_id);

  /* Returns the top three users playing a given song*/
  String getTopThreeUsersBySong (String song_id);

  /* Returns the top three songs played by a given user*/
  String getTopThreeSongsByUser (String user_id);
} // interface ProfilerOperations
