package TasteProfile;


/**
* TasteProfile/TopThreeUsers.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from tasteprofile.idl
* 26. september 2019 kl 13.06 CEST
*/

public abstract class TopThreeUsers implements org.omg.CORBA.portable.StreamableValue
{
  public TasteProfile.UserCounter topThreeUsers[] = null;

  private static String[] _truncatable_ids = {
    TasteProfile.TopThreeUsersHelper.id ()
  };

  public String[] _truncatable_ids() {
    return _truncatable_ids;
  }

  public void _read (org.omg.CORBA.portable.InputStream istream)
  {
    int _len0 = istream.read_long ();
    this.topThreeUsers = new TasteProfile.UserCounter[_len0];
    for (int _o1 = 0;_o1 < this.topThreeUsers.length; ++_o1)
      this.topThreeUsers[_o1] = TasteProfile.UserCounterHelper.read (istream);
  }

  public void _write (org.omg.CORBA.portable.OutputStream ostream)
  {
    ostream.write_long (this.topThreeUsers.length);
    for (int _i0 = 0;_i0 < this.topThreeUsers.length; ++_i0)
      TasteProfile.UserCounterHelper.write (ostream, this.topThreeUsers[_i0]);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TasteProfile.TopThreeUsersHelper.type ();
  }
} // class TopThreeUsers
