package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Friday, September 20, 2013 10:57:02 AM CEST
*/

public interface HelloOperations 
{
  String sayHello (String message);
} // interface HelloOperations
