package HelloApp;


/**
* HelloApp/TestOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 18. september 2019 kl 16.43 CEST
*/

public interface TestOperations 
{
  String getTimesPlayed (String message);
  String getTimesPlayedByUser (String message);
} // interface TestOperations
