package HelloApp;


/**
* HelloApp/Test.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 18. september 2019 kl 16.43 CEST
*/

public interface Test extends TestOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Test
