package HelloApp;

/**
* HelloApp/TestHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* 18. september 2019 kl 16.43 CEST
*/

public final class TestHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.Test value = null;

  public TestHolder ()
  {
  }

  public TestHolder (HelloApp.Test initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.TestHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.TestHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.TestHelper.type ();
  }

}
