module HelloApp
{
  interface Hello
  {
    string getTimesPlayed(in string message);
    string getTimesPlayedByUser(in string message);
  };
  interface Test
  {
    string getTimesPlayed(in string message);
    string getTimesPlayedByUser(in string message);
  };
};
